### ISSUE TITLE
Feature request: color settings

### ISSUE THREAD

**Issue by savadodesigns** [sthefanoss/flutter_multi_slider#7]
Hey! First of all, thanks for this package, it's a life safer for my desired UI.
Could you maybe add some more options for the colors? I would like to be able to set different colors for;
- The thumb
- The track
- The selected ranges on the track

**Comment by sthefanoss** [comment]
Hello @savadodesigns. Thanks for your feedback! Feel free to make some changes and sumbit a PR.

**Comment by savadodesigns** [comment]
@sthefanoss When you have the time, please review my PR https://github.com/sthefanoss/flutter_multi_slider/pull/9

**Comment by sthefanoss** [comment]
@savadodesigns thanks for your help. I'll define "indicator" as callback (instead of bool). So we can setup text format, color, etc. If we define one, it will be enabled. 

I tried to use indicator: true with my example app and it became awckard. 

I'll deliver it to pub.dev this weekend.

**Comment by sthefanoss** [comment]
@savadodesigns I add a thanks for you on package READE.ME

Now you can import directly from pubdev https://pub.dev/packages/flutter_multi_slider. 
 
I've made more ways to costumize indicators and trackbars. It's possible to change thumb indicators as well.

I'm using a callback implementation for those "builders" because its more flutterish. Your List<Colors> solution will still work (with or without mine).

 I'll need some time to document all this. You can play around with new features to see if they help you better with what you are doind and even implement more things.
